### PR TITLE
[IMP] base_report_to_print: in order to solve the issue#[163](https://github.com/OCA/report-print-send/issues/163)

### PR DESCRIPTION
**Pull request by JulioSerna**
we have tried to solve the issue with all comments into issue but does not
works, the only way that we can print it was printing from command line
with lpadmin from server of the cups

### CODE REVIEW

**Comment by moylop260** [comment]
The guy is telling that it is not working...
 - https://github.com/OCA/report-print-send/issues/163#issuecomment-435146677

But they are talking about a particular version of pycups

What about trying install another one version?

**Comment by JonathanOsAlc** [comment]
@JulioSerna Could you update this PR? DeployV can't apply this patch because it needs to be updated.

image

**Comment by moylop260** [comment]
@josemoralesp 
Should we use patches.txt instead?

**Comment by moylop260** [comment]
I just reverted the commit of vx@12.0 to use the same commits from oca@12.0
And b&f has patches using this PR.

**Pull request closed without merging**
